// @ts-expect-error Node's strip-types runner requires the explicit extension.
import { isIndexableSitemapRoute, routePolicy } from './sitemap-policy.ts'
// @ts-expect-error Node's strip-types runner requires the explicit extension.
import { searchPolicyForPath } from './search-policy.ts'

if (routePolicy('/tools/operations') !== 'UTILITY') throw new Error('operations must remain utility')
if (routePolicy('/tools/operations/status') !== 'UTILITY') throw new Error('nested operations routes must remain utility')
if (routePolicy('/operations/status') !== 'UTILITY') throw new Error('operations family must remain utility')
if (routePolicy('/search') !== 'UTILITY') throw new Error('search must remain utility')
if (routePolicy('/search/results') !== 'UTILITY') throw new Error('nested search routes must remain utility')
if (routePolicy('/stock') !== 'UTILITY') throw new Error('StockPulse hub must remain utility')
if (routePolicy('/stock/2026-09-21') !== 'UTILITY') throw new Error('StockPulse detail routes must remain utility')
if (routePolicy('/demos/html') !== 'INDEX') throw new Error('populated HTML Showcase category must remain indexable')
if (!isIndexableSitemapRoute('/labs/board')) throw new Error('Lab Board must remain in sitemap')
if (routePolicy('/labs/local-llm-benchmark') !== 'INDEX') throw new Error('measured Local LLM project must be indexable')
if (routePolicy('/labs/autonomous-ai-blog') !== 'INDEX') throw new Error('Autonomous AI Blog Project must remain indexable')
if (routePolicy('/labs/stockpulse-v1-fixed') !== 'INDEX') throw new Error('StockPulse V1 Fixed Project must be indexable')
if (routePolicy('/research/category/llm') !== 'NAVIGATION_ONLY') throw new Error('research category is navigation-only in this phase')
if (routePolicy('/lab') === 'INDEX') throw new Error('legacy Lab hub must not be sitemap-indexable')
if (!isIndexableSitemapRoute('/research')) throw new Error('Knowledge hub must remain indexable')
if (isIndexableSitemapRoute('/aitech')) throw new Error('AI Tech compact history must be excluded from sitemap')
if (!isIndexableSitemapRoute('/privacy')) throw new Error('Privacy must remain indexable')
if (!isIndexableSitemapRoute('/demos/html')) throw new Error('populated HTML Showcase category must remain in sitemap')
if (!isIndexableSitemapRoute('/demos/music')) throw new Error('populated Music Showcase category must remain in sitemap')
if (!isIndexableSitemapRoute('/demos/shortmovie')) throw new Error('populated Short Movie Showcase category must remain in sitemap')
if (isIndexableSitemapRoute('/data')) throw new Error('Data hub must be excluded until it has an independent editorial landing page')
if (isIndexableSitemapRoute('/demos')) throw new Error('Showcase hub must be excluded while categories remain indexable')
if (!isIndexableSitemapRoute('/benchmarks')) throw new Error('current public benchmark hub must remain in sitemap')
if (!isIndexableSitemapRoute('/benchmarks/custom')) throw new Error('custom benchmark collection must remain in sitemap')
if (!isIndexableSitemapRoute('/benchmarks/models/ling-3-0-flash')) throw new Error('Ling model page must remain in sitemap')
if (!isIndexableSitemapRoute('/benchmarks/models/n2-5-mini')) throw new Error('N2.5 Mini model page must remain in sitemap')
if (isIndexableSitemapRoute('/benchmarks/gb10-llm-benchmark-v1-20260906')) throw new Error('historical benchmark URL must not remain indexable')
if (isIndexableSitemapRoute('/search')) throw new Error('utility route must not be sitemap-indexable')
if (isIndexableSitemapRoute('/tools/operations/status')) throw new Error('nested operations route must not be sitemap-indexable')
if (isIndexableSitemapRoute('/operations/status')) throw new Error('operations route must not be sitemap-indexable')
if (isIndexableSitemapRoute('/stock/2026-09-21')) throw new Error('StockPulse detail route must not be sitemap-indexable')
if (isIndexableSitemapRoute('/links')) throw new Error('utility Links must not be sitemap-indexable')
if (isIndexableSitemapRoute('/data/hermes-usage')) throw new Error('usage telemetry must not be sitemap-indexable')
if (!isIndexableSitemapRoute('/labs/local-llm-benchmark')) throw new Error('measured Local LLM project must be in sitemap')
if (isIndexableSitemapRoute('/labs/stockpulse-v1-fixed/runs')) throw new Error('raw StockPulse Run Board must not be in sitemap')
if (searchPolicyForPath('/search/results') !== 'noindex') throw new Error('nested search route must be noindex')
if (searchPolicyForPath('/tools/operations/status') !== 'noindex') throw new Error('nested operations route must be noindex')
if (searchPolicyForPath('/operations/status') !== 'noindex') throw new Error('operations route must be noindex')
if (searchPolicyForPath('/data/hermes-usage/model') !== 'noindex') throw new Error('nested usage route must be noindex')
if (searchPolicyForPath('/stock/2026-09-21') !== 'noindex') throw new Error('StockPulse detail route must be noindex')
if (isIndexableSitemapRoute('/en')) throw new Error('English pilot hub must not be sitemap-indexable')
if (routePolicy('/en/benchmarks') !== 'INDEX') throw new Error('English Benchmark pilot must be an indexable collection route')
if (!isIndexableSitemapRoute('/en/benchmarks')) throw new Error('English Benchmark pilot must be in sitemap')
if (isIndexableSitemapRoute('/html5-poop-dodge-game.html')) throw new Error('raw artifact must not be sitemap-indexable')

console.log('Sitemap policy tests passed')
